# Generated by Django 3.2.8 on 2022-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_onlineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='../media/user/logo2.png', upload_to='user'),
        ),
    ]
